apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  selector:
    app.kubernetes.io/name: hello-app
  ports:
    - name: http
      port: 85
      targetPort: 8080
      nodePort: 30085
      protocol: TCP
  type: NodePort
